# DBP experiment
1. run tp-tp model and tp-dbp model
2. set k to a smaller number and verify my guess
3. use edge dataset to evaluate the knn property

* parametric_umap, tp-tp -> encoder_original
* parametric_umap_DBP,tp-tp -> encoder_core
* parametric_umap_DBP, tp-dbp -> encoder_dbp

In [1]:
# define encoder
import tensorflow as tf
physical_devices = tf.config.list_physical_devices('GPU')
tf.config.experimental.set_memory_growth(physical_devices[0], True)

In [123]:
import os
save_location = "parametric_umap_models\dbp_exp"
# load model
# load encoder
encoder_output = os.path.join(save_location, "encoder_original")
if os.path.exists(encoder_output):
    load_encoder = tf.keras.models.load_model(encoder_output)
    print("Keras encoder model loaded from {}".format(encoder_output))

# # load decoder
# decoder_output = os.path.join(save_location, "decoder_original")
# if os.path.exists(decoder_output):
#     load_decoder = tf.keras.models.load_model(decoder_output)
#     print("Keras decoder model loaded from {}".format(decoder_output))

Keras encoder model loaded from parametric_umap_models\dbp_exp\encoder_original


In [3]:
import numpy as np
train_data = np.load("train_data.npy")
train_pred_labels = np.load("train_pred_labels.npy")
test_data = np.load("test_data.npy")
test_pred_labels = np.load("test_pred_labels.npy")
border_center = np.load("border_center.npy")
border_center_labels= np.load("border_center_labels.npy")

In [4]:
N = 10

In [5]:
low_center = load_encoder(border_center).cpu().numpy()
low_train = load_encoder(train_data).cpu().numpy()

Instructions for updating:
Use tf.identity instead.


In [6]:
## nndescent?
from sklearn.neighbors import KDTree
high_tree = KDTree(border_center) 
low_tree = KDTree(low_center)

In [7]:
_, high_ind = high_tree.query(train_data, k=N) 
_, low_ind = low_tree.query(low_train, k=N) 

In [8]:
border_pres = np.zeros(len(train_data))
for i in range(len(train_data)):
    border_pres[i] = len(np.intersect1d(high_ind[i],low_ind[i]))

In [13]:
np.bincount(border_pres.astype("int64"))

array([32185,  9015,  2494,  1806,  3116,  1093,   162,    66,    49,
          13,     1], dtype=int64)

In [127]:
import os
save_location = "parametric_umap_models\dbp_exp"
# load model
# load encoder
encoder_output = os.path.join(save_location, "encoder_core")
if os.path.exists(encoder_output):
    load_encoder = tf.keras.models.load_model(encoder_output)
    print("Keras encoder model loaded from {}".format(encoder_output))

# # load decoder
# decoder_output = os.path.join(save_location, "decoder_core")
# if os.path.exists(decoder_output):
#     load_decoder = tf.keras.models.load_model(decoder_output)
#     print("Keras decoder model loaded from {}".format(decoder_output))

Keras encoder model loaded from parametric_umap_models\dbp_exp\encoder_core


In [15]:
low_center = load_encoder(border_center).cpu().numpy()
low_train = load_encoder(train_data).cpu().numpy()

In [16]:
## nndescent?
from sklearn.neighbors import KDTree
high_tree = KDTree(border_center) 
low_tree = KDTree(low_center)

In [17]:
_, high_ind = high_tree.query(train_data, k=N) 
_, low_ind = low_tree.query(low_train, k=N) 

In [18]:
border_pres = np.zeros(len(train_data))
for i in range(len(train_data)):
    border_pres[i] = len(np.intersect1d(high_ind[i],low_ind[i]))

In [19]:
np.bincount(border_pres.astype("int64"))

array([22767, 10797,  6282,  5752,  2907,  1162,   306,    15,    12],
      dtype=int64)

In [131]:
import os
save_location = "parametric_umap_models\dbp_exp"
# load model
# load encoder
encoder_output = os.path.join(save_location, "encoder_dbp")
if os.path.exists(encoder_output):
    load_encoder = tf.keras.models.load_model(encoder_output)
    print("Keras encoder model loaded from {}".format(encoder_output))

# # load decoder
# decoder_output = os.path.join(save_location, "decoder_dbp")
# if os.path.exists(decoder_output):
#     load_decoder = tf.keras.models.load_model(decoder_output)
#     print("Keras decoder model loaded from {}".format(decoder_output))

Keras encoder model loaded from parametric_umap_models\dbp_exp\encoder_dbp


In [21]:
low_center = load_encoder(border_center).cpu().numpy()
low_train = load_encoder(train_data).cpu().numpy()

In [22]:
## nndescent?
from sklearn.neighbors import KDTree
high_tree = KDTree(border_center) 
low_tree = KDTree(low_center)

In [23]:
_, high_ind = high_tree.query(train_data, k=N) 
_, low_ind = low_tree.query(low_train, k=N) 

In [24]:
border_pres = np.zeros(len(train_data))
for i in range(len(train_data)):
    border_pres[i] = len(np.intersect1d(high_ind[i],low_ind[i]))

In [25]:
np.bincount(border_pres.astype("int64"))

array([33452,  9499,  5792,   465,   302,   184,   117,    94,    66,
          28,     1], dtype=int64)

In [135]:
import os
save_location = "parametric_umap_models\dbp_exp"
# load model
# load encoder
encoder_output = os.path.join(save_location, "encoder_withouttp")
if os.path.exists(encoder_output):
    load_encoder = tf.keras.models.load_model(encoder_output)
    print("Keras encoder model loaded from {}".format(encoder_output))

# # load decoder
# decoder_output = os.path.join(save_location, "decoder_dbp")
# if os.path.exists(decoder_output):
#     load_decoder = tf.keras.models.load_model(decoder_output)
#     print("Keras decoder model loaded from {}".format(decoder_output))

Keras encoder model loaded from parametric_umap_models\dbp_exp\encoder_withouttp


In [30]:
low_center = load_encoder(border_center).cpu().numpy()
low_train = load_encoder(train_data).cpu().numpy()

In [31]:
## nndescent?
from sklearn.neighbors import KDTree
high_tree = KDTree(border_center) 
low_tree = KDTree(low_center)

In [32]:
_, high_ind = high_tree.query(train_data, k=N) 
_, low_ind = low_tree.query(low_train, k=N) 

In [33]:
border_pres = np.zeros(len(train_data))
for i in range(len(train_data)):
    border_pres[i] = len(np.intersect1d(high_ind[i],low_ind[i]))

In [34]:
np.bincount(border_pres.astype("int64"))

array([42618,  6516,   237,   148,   140,   118,    89,    93,    39,
           2], dtype=int64)

In [37]:
len(border_pres)-np.count_nonzero(border_pres)

42618

# create the edge dataset

In [60]:
batch_size = 20

train_num = 50000
augmentation_num = 10000
border_num = 5000

fitting_data = np.concatenate((train_data[-train_num:],
#                                augmentation_data[:augmentation_num],
                               border_center[:border_num]), axis=0)
fitting_data.shape

(55000, 2048)

In [61]:
# number of trees in random projection forest
n_trees = 5 + int(round((fitting_data.shape[0]) ** 0.5 / 20.0))
# max number of nearest neighbor iters to perform
n_iters = max(5, int(round(np.log2(fitting_data.shape[0]))))
# distance metric
metric = "euclidean"
# number of neighbors for computing k-neighbor graph
n_neighbors = 15

In [62]:
from pynndescent import NNDescent
# get nearest neighbors
nnd = NNDescent(
    fitting_data.reshape((len(fitting_data), np.product(np.shape(fitting_data)[1:]))),
    n_neighbors=n_neighbors,
    metric=metric,
    n_trees=n_trees,
    n_iters=n_iters,
    max_candidates=60,
    verbose=True
)

Wed Jan 13 19:21:17 2021 Building RP forest with 17 trees
Wed Jan 13 19:21:20 2021 NN descent for 16 iterations
	 1  /  16
	 2  /  16
	 3  /  16
	Stopping threshold met -- exiting after 3 iterations


In [63]:
from sklearn.utils import check_random_state
from umap.umap_ import fuzzy_simplicial_set
knn_indices, knn_dists = nnd.neighbor_graph
random_state = check_random_state(None)

In [64]:
umap_graph, sigmas, rhos, dists = fuzzy_simplicial_set(
    X=fitting_data,
    n_neighbors=n_neighbors,
    metric=metric,
    random_state=random_state,
    knn_indices=knn_indices,
    knn_dists=knn_dists,
    return_dists=True,
)

In [65]:
graph = umap_graph.tocoo()
graph.sum_duplicates()
graph.eliminate_zeros()
graph.data[graph.data < (graph.data.max() / float(500))] = 0.0
graph.eliminate_zeros()
graph

<55000x55000 sparse matrix of type '<class 'numpy.float32'>'
	with 1099766 stored elements in COOrdinate format>

In [80]:
head,tail,weight= graph.row,graph.col,graph.data
len(head),len(tail)

(1099766, 1099766)

In [81]:
tp_head = (head<50000)
tp_tail = (tail<50000)
tp_tp = (tp_head & tp_tail)
np.sum(tp_tp)

1003620

In [82]:
dbp_head = (head>=50000)
dbp_tail = (tail>=50000)
dbp_dbp = (dbp_head & dbp_tail)
np.sum(dbp_dbp)

85116

In [83]:
tp_dbp = ((tp_head & dbp_tail) | (dbp_head & tp_tail))
np.sum(tp_dbp)

11030

In [85]:
tp_dbp = (tp_head & dbp_tail)
np.sum(tp_dbp)

5515

In [91]:
edges = np.argwhere(tp_dbp==True)
edges = np.squeeze(edges)
edges

array([1009135, 1009136, 1009137, ..., 1099649, 1099650, 1099666],
      dtype=int64)

In [124]:
# tp-tp
low_fitting_data = load_encoder(fitting_data).cpu().numpy()

In [125]:
dists = np.zeros(len(edges))
for i in range(len(edges)):
    h = low_fitting_data[head[edges[i]]]
    t = low_fitting_data[tail[edges[i]]]
    dists[i] = np.linalg.norm(h-t)
dists.mean(), np.std(dists,axis=0)

(2.6621539374880987, 2.76190855788689)

In [126]:
dists = np.zeros(len(edges))
for i in range(len(edges)):
    h = low_fitting_data[head[edges[i]]]
    t = low_fitting_data[tail[neg[i]]]
    dists[i] = np.linalg.norm(h-t)
dists.mean(), np.std(dists,axis=0)

(11.881431530302024, 8.13159089576581)

In [128]:
# tp-tp core
low_fitting_data = load_encoder(fitting_data).cpu().numpy()

In [129]:
dists = np.zeros(len(edges))
for i in range(len(edges)):
    h = low_fitting_data[head[edges[i]]]
    t = low_fitting_data[tail[edges[i]]]
    dists[i] = np.linalg.norm(h-t)
dists.mean(), np.std(dists,axis=0)

(3.240253884779291, 3.6968340137081337)

In [130]:
dists = np.zeros(len(edges))
for i in range(len(edges)):
    h = low_fitting_data[head[edges[i]]]
    t = low_fitting_data[tail[neg[i]]]
    dists[i] = np.linalg.norm(h-t)
dists.mean(), np.std(dists,axis=0)

(15.441977167531428, 10.332535596078399)

In [132]:
# tp-dbp
low_fitting_data = load_encoder(fitting_data).cpu().numpy()

In [133]:
dists = np.zeros(len(edges))
for i in range(len(edges)):
    h = low_fitting_data[head[edges[i]]]
    t = low_fitting_data[tail[edges[i]]]
    dists[i] = np.linalg.norm(h-t)
dists.mean(), np.std(dists,axis=0)

(0.6543270221647088, 0.41393987605949595)

In [134]:
dists = np.zeros(len(edges))
for i in range(len(edges)):
    h = low_fitting_data[head[edges[i]]]
    t = low_fitting_data[tail[neg[i]]]
    dists[i] = np.linalg.norm(h-t)
dists.mean(), np.std(dists,axis=0)

(4.838728493410867, 2.3704286107589785)

In [136]:
# tp-dbp+dbp-dbp
low_fitting_data = load_encoder(fitting_data).cpu().numpy()

In [137]:
dists = np.zeros(len(edges))
for i in range(len(edges)):
    h = low_fitting_data[head[edges[i]]]
    t = low_fitting_data[tail[edges[i]]]
    dists[i] = np.linalg.norm(h-t)
dists.mean(), np.std(dists,axis=0)

(0.5080731251336978, 0.5900279612300334)

In [138]:
dists = np.zeros(len(edges))
for i in range(len(edges)):
    h = low_fitting_data[head[edges[i]]]
    t = low_fitting_data[tail[neg[i]]]
    dists[i] = np.linalg.norm(h-t)
dists.mean(), np.std(dists,axis=0)

(5.379653172588765, 2.761048049037231)

In [111]:
neg = np.random.permutation(len(edges))
neg = edges[neg]

(5.379653172588765, 2.761048049037231)